import { useState } from 'react';

import type { AgentCard, Citation, FactCitation, PassageCitation } from './types';
import { useCitations } from './CitationContext';

/** Turn a raw field path (`net_worth_cents`) into a readable label ("Net worth"). */
function humanizeField(field: string): string {
  const base = field
    .replace(/_(cents|bps)$/i, '')
    .replace(/_/g, ' ')
    .trim();
  return base.charAt(0).toUpperCase() + base.slice(1);
}

/**
 * Deduplicate fact citations by the field they point at, keeping the first occurrence. Agents often
 * cite the same field many times (e.g. "Expected value" per offer, repeated "Total"s), which floods
 * the list with identical pills; one pill per distinct field carries the same jump targets without
 * the repetition. No information is lost — the first citation for a field resolves to that field's
 * card, which is all a duplicate pill would do.
 */
function dedupeFacts(facts: readonly FactCitation[]): readonly FactCitation[] {
  const seen = new Set<string>();
  const out: FactCitation[] = [];
  for (const fact of facts) {
    const key = `${fact.entity_type}.${fact.field}`;
    if (seen.has(key)) {
      continue;
    }
    seen.add(key);
    out.push(fact);
  }
  return out;
}

/** How many citation pills to show before collapsing the rest behind "See more". */
const CITATION_PREVIEW = 6;

/** A collapsible list of citation pills: shows the first few, with a "See more" for the rest. */
function CitationPills({
  citations,
}: {
  readonly citations: readonly Citation[];
}): React.JSX.Element {
  const [expanded, setExpanded] = useState(false);
  const isLong = citations.length > CITATION_PREVIEW;
  const visible = expanded || !isLong ? citations : citations.slice(0, CITATION_PREVIEW);
  return (
    <>
      <ul className="citations__list">
        {visible.map((citation) => (
          <li key={citation.kind === 'fact' ? citation.fact_id : citation.passage_id}>
            <CitationChip citation={citation} />
          </li>
        ))}
      </ul>
      {isLong && (
        <button
          type="button"
          className="citations__more focus-ring"
          aria-expanded={expanded}
          onClick={() => {
            setExpanded((v) => !v);
          }}
        >
          {expanded ? 'See less' : `See ${citations.length - CITATION_PREVIEW} more`}
        </button>
      )}
    </>
  );
}

/**
 * The shared chrome every AI surface wears (tasks 14.1, 14.2, 14.4).
 *
 * Two obligations run through the whole AI layer and are met here once:
 *
 * - **Honest labelling.** Anything a model produced is labelled as AI-generated, stamped with the
 *   time it was generated, marked when it came from cache, and — when the model was unavailable and
 *   a deterministic template stood in — badged as degraded (requirements 10.1, 10.12). {@link AiMeta}
 *   renders that strip from an {@link AgentCard}'s metadata.
 * - **Traceable claims.** Every figure or piece of guidance in a narrative resolves to a citation.
 *   {@link CitationList} renders the two kinds distinctly (design §9.1): a fact chip opens the owning
 *   widget and highlights the field; a knowledge chip opens the passage viewer. Unavailable inputs
 *   are stated plainly rather than hidden, so a card never implies completeness it does not have
 *   (requirement 10.9).
 */

// ---------------------------------------------------------------- labels and badges

/** The "AI-generated" label every model surface carries (requirement 10.1). */
export function AiLabel(): React.JSX.Element {
  return (
    <span className="ai-label" title="Generated by an AI model">
      <span aria-hidden="true">✦</span> AI-generated
    </span>
  );
}

/** The degraded badge shown when a card fell back to a deterministic template (requirement 10.12). */
export function DegradedBadge(): React.JSX.Element {
  return (
    <span
      className="badge badge--degraded"
      title="The AI model was unavailable; this is a deterministic fallback."
    >
      Degraded
    </span>
  );
}

/** The metadata strip: AI label, generation time, cache indicator and degraded badge. */
export function AiMeta({ card }: { readonly card: AgentCard }): React.JSX.Element {
  return (
    <div className="ai-meta">
      <AiLabel />
      {card.degraded && <DegradedBadge />}
      {card.cache_hit && (
        <span className="badge badge--cache" title="Served from cache">
          Cached
        </span>
      )}
      <time className="ai-meta__time" dateTime={card.generated_at}>
        {formatGeneratedAt(card.generated_at)}
      </time>
      {card.confidence !== null && (
        <span className="ai-meta__confidence">Confidence {Math.round(card.confidence * 100)}%</span>
      )}
    </div>
  );
}

function formatGeneratedAt(iso: string): string {
  const parsed = new Date(iso);
  if (Number.isNaN(parsed.getTime())) {
    return iso;
  }
  return `Generated ${parsed.toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })}`;
}

// ---------------------------------------------------------------- citations

/**
 * A single citation rendered as an inspectable source pill; the two kinds look and behave
 * differently (design §9.1). A **fact** pill jumps to the owning widget and highlights the field —
 * so it shows a readable field name and a "go to" arrow, not a web-link glyph. A **knowledge** pill
 * opens the source passage. Both are buttons; the arrow/label make the interactivity obvious.
 */
export function CitationChip({ citation }: { readonly citation: Citation }): React.JSX.Element {
  const { inspectFact, inspectPassage } = useCitations();
  if (citation.kind === 'fact') {
    return (
      <button
        type="button"
        className="citation citation--fact"
        onClick={() => {
          inspectFact(citation);
        }}
        title={`Go to ${humanizeField(citation.field)} in the ${citation.entity_type} card`}
      >
        <span className="citation__icon" aria-hidden="true">
          ◎
        </span>
        <span className="citation__text">{humanizeField(citation.field)}</span>
        <span className="citation__go" aria-hidden="true">
          ↗
        </span>
      </button>
    );
  }
  return (
    <button
      type="button"
      className="citation citation--passage"
      onClick={() => {
        inspectPassage(citation);
      }}
      title={`Open source: ${citation.title} · ${citation.section_path}`}
    >
      <span className="citation__icon" aria-hidden="true">
        📄
      </span>
      <span className="citation__text">{citation.title}</span>
      <span className="citation__go" aria-hidden="true">
        ↗
      </span>
    </button>
  );
}

/**
 * The two citation lists for a card, kept apart and labelled: facts first, then knowledge. Empty
 * lists render nothing; unavailable inputs are surfaced explicitly beneath them.
 */
export function CitationList({
  facts,
  passages,
  unavailableInputs = [],
}: {
  readonly facts: readonly FactCitation[];
  readonly passages: readonly PassageCitation[];
  readonly unavailableInputs?: readonly string[];
}): React.JSX.Element | null {
  const uniqueFacts = dedupeFacts(facts);
  const hasFacts = uniqueFacts.length > 0;
  const hasPassages = passages.length > 0;
  const hasUnavailable = unavailableInputs.length > 0;
  if (!hasFacts && !hasPassages && !hasUnavailable) {
    return null;
  }
  return (
    <div className="citations">
      {hasFacts && (
        <div className="citations__group">
          <span className="citations__label">
            <span className="citations__label-icon" aria-hidden="true">
              📌
            </span>
            <span className="citations__label-text">Facts</span>
            <span className="citations__count">{uniqueFacts.length}</span>
            <span className="citations__hint">click to jump to the card</span>
          </span>
          <CitationPills citations={uniqueFacts} />
        </div>
      )}
      {hasPassages && (
        <div className="citations__group">
          <span className="citations__label">
            <span className="citations__label-icon" aria-hidden="true">
              📚
            </span>
            <span className="citations__label-text">Knowledge</span>
            <span className="citations__count">{passages.length}</span>
            <span className="citations__hint">click to open the passage</span>
          </span>
          <CitationPills citations={passages} />
        </div>
      )}
      {hasUnavailable && (
        <p className="citations__unavailable">
          Some inputs were unavailable: {unavailableInputs.join(', ')}.
        </p>
      )}
    </div>
  );
}
