"""SQLite adapter for :class:`~c360.domain.ports.FinancialRepository` (task 1.6).

Holdings are assembled from five statements, not from one join and not from one query per account.

A single join across ``account`` and all four specializations would need every specialization column
aliased to avoid collisions on ``account_id``, and mapping that back onto four models means
unpicking
prefixes — a lot of mechanical code whose failure mode is a silently mis-assigned column. A query
per
account would be an N+1 on the read that requirement 5.3 puts on the dashboard's critical path.

So: one statement for the accounts, then one per specialization *that is actually present* among
them,
each fetching the whole set for the customer in one round trip. A customer holding only deposits and
a
card costs three statements; the count is bounded by five regardless of how many accounts they hold.

Aggregation happens in SQL. Both sides are integers so design §1.1's exactness guarantee holds
either
way, but folding twenty thousand rows in Python would spend the latency budget on data movement.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from c360.data.repositories.base import (
    SqliteRepository,
    Statement,
    expand_in_clause,
    optional_model,
    to_models,
)
from c360.domain.enums import AccountStatus, AccountType
from c360.domain.models import (
    Account,
    CategoryTotal,
    CreditCard,
    CreditProfile,
    Deposit,
    FinancialProfile,
    Holding,
    Investment,
    Loan,
    MonthlyTotal,
    ProductDetail,
    Transaction,
)

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence
    from datetime import date

    from c360.domain.models import SourcedModel

_FINANCIAL_PROFILE = Statement(
    id="financial.profile",
    collection="financial_profile",
    sql="""
    SELECT fp.customer_id, fp.total_deposits_cents, fp.total_loans_cents,
           fp.total_investments_cents, fp.total_assets_cents, fp.total_liabilities_cents,
           fp.net_worth_cents, fp.household_net_worth_cents, fp.monthly_income_cents,
           fp.monthly_expense_cents, fp.as_of_date, c.source_system
    FROM financial_profile fp
    JOIN customer c ON c.customer_id = fp.customer_id
    WHERE fp.customer_id = :customer_id
    """,
)

_CREDIT_PROFILE = Statement(
    id="financial.credit_profile",
    collection="credit_profile",
    sql="""
    SELECT cp.customer_id, cp.fico_score, cp.behavior_score, cp.propensity_score,
           cp.credit_utilization_bps, cp.years_on_bureau, cp.num_inquiries, cp.num_trades,
           cp.num_credit_accounts, cp.credit_exposure_cents, cp.as_of_date, c.source_system
    FROM credit_profile cp
    JOIN customer c ON c.customer_id = cp.customer_id
    WHERE cp.customer_id = :customer_id
    """,
)

_ACCOUNT_COLUMNS = """
    a.account_id, a.customer_id, a.account_number, a.account_type, a.product_name, a.product_code,
    a.balance_cents, a.available_balance_cents, a.interest_rate_bps, a.account_status,
    a.open_date, a.close_date, a.as_of_date, c.source_system
"""

#: Ordering is by account type then ID so a holdings list is stable between calls. Requirement
# 14.7's
#: reproducibility and the byte-identical-output test in task 2.1 both depend on reads not
# shuffling.
_HOLDINGS_ORDER = "ORDER BY a.account_type, a.account_id"


def _holdings_statement(
    *,
    type_placeholders: str | None,
    status_placeholders: str | None,
) -> Statement:
    """Build the accounts statement, with optional ``IN`` filters.

    The statement ID stays ``financial.holdings_accounts`` regardless of which filters are applied.
    That is the point of having an ID: a trace groups every variant of this read together instead of
    fragmenting into one span name per filter combination, which is what design §13.4's cardinality
    rule asks for.
    """
    clauses = ["a.customer_id = :customer_id"]
    if type_placeholders:
        clauses.append(f"a.account_type IN ({type_placeholders})")
    if status_placeholders:
        clauses.append(f"a.account_status IN ({status_placeholders})")
    return Statement(
        id="financial.holdings_accounts",
        collection="account",
        # constant or a placeholder name generated by `expand_in_clause`; the caller's *values* are
        # bound, never formatted. That distinction is the whole reason `expand_in_clause` exists.
        sql=f"""
        SELECT {_ACCOUNT_COLUMNS}
        FROM account a
        JOIN customer c ON c.customer_id = a.customer_id
        WHERE {" AND ".join(clauses)}
        {_HOLDINGS_ORDER}
        """,  # noqa: S608
    )


_DEPOSITS = Statement(
    id="financial.holdings_deposit",
    collection="deposit",
    sql="""
    SELECT d.account_id, d.product_type, d.household_deposits_cents, d.maturity_date
    FROM deposit d
    JOIN account a ON a.account_id = d.account_id
    WHERE a.customer_id = :customer_id
    """,
)

_LOANS = Statement(
    id="financial.holdings_loan",
    collection="loan",
    sql="""
    SELECT l.account_id, l.loan_number, l.loan_type, l.original_amount_cents, l.monthly_emi_cents,
           l.loan_status, l.loan_start_date, l.loan_end_date, l.collateral_asset_id
    FROM loan l
    JOIN account a ON a.account_id = l.account_id
    WHERE a.customer_id = :customer_id
    """,
)

_CARDS = Statement(
    id="financial.holdings_card",
    collection="credit_card",
    # `card_number` is absent from the projection. Design §4.3 keeps the full PAN out of hot paths,
    # and a column that is never selected cannot be leaked by a masking rule someone forgot to add.
    sql="""
    SELECT cc.account_id, cc.card_last4, cc.card_type, cc.credit_limit_cents, cc.utilization_bps,
           cc.rewards_balance_cents, cc.monthly_spend_cents, cc.overlimit_events, cc.fraud_alerts
    FROM credit_card cc
    JOIN account a ON a.account_id = cc.account_id
    WHERE a.customer_id = :customer_id
    """,
)

_INVESTMENTS = Statement(
    id="financial.holdings_investment",
    collection="investment",
    sql="""
    SELECT i.account_id, i.portfolio_value_cents, i.asset_allocation, i.mutual_funds_cents,
           i.stocks_cents, i.bonds_cents, i.retirement_accounts_cents, i.investment_risk_profile
    FROM investment i
    JOIN account a ON a.account_id = i.account_id
    WHERE a.customer_id = :customer_id
    """,
)

#: Which specialization statement and model belong to each account type.
_SPECIALIZATIONS: dict[AccountType, tuple[Statement, type[SourcedModel]]] = {
    AccountType.DEPOSIT: (_DEPOSITS, Deposit),
    AccountType.LOAN: (_LOANS, Loan),
    AccountType.CARD: (_CARDS, CreditCard),
    AccountType.INVESTMENT: (_INVESTMENTS, Investment),
}

_TRANSACTION_COLUMNS = """
    t.transaction_id, t.account_id, t.customer_id, t.transaction_date, t.amount_cents,
    t.transaction_type, t.transaction_category, t.merchant, t.channel, t.status,
    t.transaction_date AS as_of_date, c.source_system
"""


def _transactions_statement(category_placeholders: str | None) -> Statement:
    """Build the transaction statement.

    Scalar filters use ``:param IS NULL OR ...`` so the common case is one static statement. Only
    the
    variable-length category list needs generated placeholders.

    ``as_of_date`` is the transaction date itself. A transaction is an event, so the date it
    happened
    *is* its as-of; there is no separate observation date to report for requirement 4.8.
    """
    clauses = [
        "t.customer_id = :customer_id",
        "(:start_date IS NULL OR t.transaction_date >= :start_date)",
        "(:end_date IS NULL OR t.transaction_date <= :end_date)",
    ]
    if category_placeholders:
        clauses.append(f"t.transaction_category IN ({category_placeholders})")
    return Statement(
        id="financial.transactions",
        collection="txn",
        # Interpolated parts are constants and generated placeholder names only; see the note in
        # `_holdings_statement`.
        sql=f"""
        SELECT {_TRANSACTION_COLUMNS}
        FROM txn t
        JOIN customer c ON c.customer_id = t.customer_id
        WHERE {" AND ".join(clauses)}
        ORDER BY t.transaction_date DESC, t.transaction_id
        LIMIT :limit
        """,  # noqa: S608
    )


# Spend, not net flow: debits only, re-signed positive. Requirement 5.8 is about where the money
# goes, and mixing salary credits into a category distribution would net a month's grocery spend
# against a paycheque and report the difference as "spending".
_TOTALS_BY_CATEGORY = Statement(
    id="financial.totals_by_category",
    collection="txn",
    sql="""
    SELECT transaction_category,
           -SUM(amount_cents) AS total_cents,
           COUNT(*)           AS transaction_count
    FROM txn
    WHERE customer_id = :customer_id
      AND amount_cents < 0
      AND (:start_date IS NULL OR transaction_date >= :start_date)
      AND (:end_date IS NULL OR transaction_date <= :end_date)
    GROUP BY transaction_category
    ORDER BY total_cents DESC, transaction_category
    """,
)

_MONTHLY_TOTALS = Statement(
    id="financial.monthly_totals",
    collection="txn",
    # `substr` rather than `strftime('%Y-%m', ...)`: the column is already a fixed-width ISO date
    # enforced by a CHECK constraint, so the first seven characters *are* the month, and substr
    # leaves the value comparable to the index without a function wrapping the indexed column.
    sql="""
    SELECT substr(transaction_date, 1, 7) AS month,
           -SUM(amount_cents)             AS total_cents,
           COUNT(*)                       AS transaction_count
    FROM txn
    WHERE customer_id = :customer_id
      AND amount_cents < 0
      AND (:category IS NULL OR transaction_category = :category)
    GROUP BY month
    ORDER BY month DESC
    LIMIT :months
    """,
)

_MEDIAN_DEBIT = Statement(
    id="financial.median_debit",
    collection="txn",
    # The lower median for an even count, which is deterministic and needs no averaging — averaging
    # the middle two would produce a half-cent and put a rounding decision in the middle of a read.
    sql="""
    SELECT abs(amount_cents)
    FROM txn
    WHERE customer_id = :customer_id AND amount_cents < 0
    ORDER BY abs(amount_cents)
    LIMIT 1
    OFFSET (
      SELECT COUNT(*) / 2 FROM txn WHERE customer_id = :customer_id AND amount_cents < 0
    )
    """,
)


class SqliteFinancialRepository(SqliteRepository):
    """Reads backing requirements 5.1 through 5.10."""

    def get_financial_profile(self, customer_id: str) -> FinancialProfile | None:
        return optional_model(
            FinancialProfile, self.fetch_one(_FINANCIAL_PROFILE, {"customer_id": customer_id})
        )

    def get_credit_profile(self, customer_id: str) -> CreditProfile | None:
        return optional_model(
            CreditProfile, self.fetch_one(_CREDIT_PROFILE, {"customer_id": customer_id})
        )

    # ---------------------------------------------------------------- holdings
    def list_holdings(
        self,
        customer_id: str,
        *,
        account_types: Sequence[AccountType] | None = None,
        statuses: Sequence[AccountStatus] | None = None,
    ) -> Sequence[Holding]:
        params: dict[str, Any] = {"customer_id": customer_id}
        type_placeholders = status_placeholders = None

        if account_types is not None:
            if not account_types:
                # An explicitly empty filter means "no types", which matches nothing. Returning
                # early
                # is not just an optimization: `IN ()` is a syntax error in SQLite, and treating the
                # empty list as "no filter" would silently return everything — the opposite of
                # asked.
                return ()
            type_placeholders, bindings = expand_in_clause(
                "account_type", [str(value) for value in account_types]
            )
            params.update(bindings)
        if statuses is not None:
            if not statuses:
                return ()
            status_placeholders, bindings = expand_in_clause(
                "account_status", [str(value) for value in statuses]
            )
            params.update(bindings)

        rows = self.fetch_all(
            _holdings_statement(
                type_placeholders=type_placeholders,
                status_placeholders=status_placeholders,
            ),
            params,
        )
        accounts = to_models(Account, rows)
        if not accounts:
            return ()

        details = self._load_details(customer_id, accounts)
        return tuple(
            Holding(account=account, detail=details.get(account.account_id)) for account in accounts
        )

    def _load_details(
        self,
        customer_id: str,
        accounts: Sequence[Account],
    ) -> Mapping[str, ProductDetail]:
        """Fetch the specializations for the account types present, keyed by account ID.

        Provenance is inherited from the parent account: the specialization tables carry no
        ``as_of_date`` or ``source_system`` of their own, and a card's credit limit is as-of the
        same
        observation as the balance it sits beside.
        """
        provenance = {
            account.account_id: (account.as_of_date, account.source_system) for account in accounts
        }
        present = {account.account_type for account in accounts}
        details: dict[str, ProductDetail] = {}

        for account_type in sorted(present):
            statement, model = _SPECIALIZATIONS[account_type]
            rows = self.fetch_all(statement, {"customer_id": customer_id})
            for row in rows:
                data = dict(row._mapping)
                account_id = str(data["account_id"])
                if account_id not in provenance:
                    # The specialization statements fetch every row for the customer, while
                    # `accounts` may have been narrowed by a type or status filter. A deposit row
                    # for
                    # an excluded closed account is expected here, not an error.
                    continue
                data["as_of_date"], data["source_system"] = provenance[account_id]
                # `model` is one of the four specializations, each a ProductDetail member.
                details[account_id] = model.model_validate(data)  # type: ignore[assignment]
        return details

    # ---------------------------------------------------------------- transactions
    def list_transactions(
        self,
        customer_id: str,
        *,
        start_date: date | None = None,
        end_date: date | None = None,
        categories: Sequence[str] | None = None,
        limit: int = 500,
    ) -> Sequence[Transaction]:
        if limit < 1:
            raise ValueError(f"limit must be at least 1, got {limit}")
        params: dict[str, Any] = {
            "customer_id": customer_id,
            "start_date": _as_iso(start_date),
            "end_date": _as_iso(end_date),
            "limit": limit,
        }
        placeholders = None
        if categories is not None:
            if not categories:
                return ()
            placeholders, bindings = expand_in_clause("category", list(categories))
            params.update(bindings)
        rows = self.fetch_all(_transactions_statement(placeholders), params)
        return to_models(Transaction, rows)

    def totals_by_category(
        self,
        customer_id: str,
        *,
        start_date: date | None = None,
        end_date: date | None = None,
    ) -> Sequence[CategoryTotal]:
        rows = self.fetch_all(
            _TOTALS_BY_CATEGORY,
            {
                "customer_id": customer_id,
                "start_date": _as_iso(start_date),
                "end_date": _as_iso(end_date),
            },
        )
        return to_models(CategoryTotal, rows)

    def monthly_totals(
        self,
        customer_id: str,
        *,
        category: str | None = None,
        months: int = 12,
    ) -> Sequence[MonthlyTotal]:
        if months < 1:
            raise ValueError(f"months must be at least 1, got {months}")
        rows = self.fetch_all(
            _MONTHLY_TOTALS,
            {"customer_id": customer_id, "category": category, "months": months},
        )
        # Fetched newest-first so `LIMIT` takes the most recent months; returned oldest-first
        # because a trend series reads forwards.
        return tuple(reversed(to_models(MonthlyTotal, rows)))

    def median_transaction_amount_cents(self, customer_id: str) -> int | None:
        value = self.fetch_scalar(_MEDIAN_DEBIT, {"customer_id": customer_id})
        return None if value is None else int(value)


def _as_iso(value: date | None) -> str | None:
    """Bind a date as the ISO text SQLite stores.

    Passing a ``date`` object through the driver would bind it as a string via its ``__str__``,
    which
    happens to be the same thing — but relying on that couples correctness to a dunder. Doing it
    explicitly also means the comparison is text-to-text against a fixed-width column, which is what
    makes the range predicate index-usable.
    """
    return None if value is None else value.isoformat()
